# we will use node:alpine docker image
FROM node:21-alpine

ENV NODE_ENV=development
# set /app as work directory
WORKDIR /app

# copy package.json to work directory, so that we install npm dependencies
COPY package.json /app

# install npm dependencies
RUN npm install

# copy your project files to work directory
COPY . /app

# run your app
CMD ["npm", "run", "dev"]
